name: ticket_flight_exam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.4.1
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  provider: ^6.1.2
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
