// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEbYsf79jaz_BYZ0Z6daBYbgjIsv0tLNw',
    appId: '1:1004519723752:web:6af7b98936052afff62f5d',
    messagingSenderId: '1004519723752',
    projectId: 'electionstest-a6f8d',
    authDomain: 'electionstest-a6f8d.firebaseapp.com',
    storageBucket: 'electionstest-a6f8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCFAgeINRHGqoR-bWbaAt-EeLgm9DzGeE',
    appId: '1:1004519723752:android:f8335c2d6ea2730df62f5d',
    messagingSenderId: '1004519723752',
    projectId: 'electionstest-a6f8d',
    storageBucket: 'electionstest-a6f8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9gB2YvTqW4sGzoHArnU4KKj3KxXfGk2o',
    appId: '1:1004519723752:ios:3d3c66edcde39754f62f5d',
    messagingSenderId: '1004519723752',
    projectId: 'electionstest-a6f8d',
    storageBucket: 'electionstest-a6f8d.appspot.com',
    iosBundleId: 'com.example.ticketFlightExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9gB2YvTqW4sGzoHArnU4KKj3KxXfGk2o',
    appId: '1:1004519723752:ios:3d3c66edcde39754f62f5d',
    messagingSenderId: '1004519723752',
    projectId: 'electionstest-a6f8d',
    storageBucket: 'electionstest-a6f8d.appspot.com',
    iosBundleId: 'com.example.ticketFlightExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEbYsf79jaz_BYZ0Z6daBYbgjIsv0tLNw',
    appId: '1:1004519723752:web:35886219220e8fbdf62f5d',
    messagingSenderId: '1004519723752',
    projectId: 'electionstest-a6f8d',
    authDomain: 'electionstest-a6f8d.firebaseapp.com',
    storageBucket: 'electionstest-a6f8d.appspot.com',
  );
}
